name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      SAM_CONFIG_FILE: ${{ github.workspace }}/samconfig.toml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate
        run: sam validate --template-file infra/template.yaml --config-file "$SAM_CONFIG_FILE" --config-env dev --lint

      - name: Build
        run: sam build --template-file infra/template.yaml --config-file "$SAM_CONFIG_FILE" --config-env dev

      - name: Deploy
        run: sam deploy --template-file infra/template.yaml --config-file "$SAM_CONFIG_FILE" --config-env dev --no-confirm-changeset --no-fail-on-empty-changeset
